version: "3"
services:
    postgres:
        container_name: vodokachka-db
        image: postgres:latest
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - data:/var/lib/postgresql/data
        networks:
            - postgres
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}

networks:
    postgres:
        driver: bridge

volumes:
    data:
